// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using ProceduresTest.Entities;

namespace ProceduresTest.Data
{
    public partial class AppDbContext
    {

        [DbFunction("fn_GetCount", "dbo")]
        public static int? fn_GetCount()
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
        }
    }
}
