// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using ProceduresTest.Entities;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace ProceduresTest.Data
{
    public partial interface IAppDbContextProcedures
    {
        Task<List<Usp_Company_detailsResult>> Usp_Company_detailsAsync(string Id, string search, int? PageNum, int? PageSize, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> Usp_Company_UpdateAsync(int? Action, string Name, string State, string City, string Address, OutputParameter<string> Result, OutputParameter<string> Id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
